// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/api/image/[filename].ts";
import * as $1 from "./routes/api/interactive/[...folder].ts";
import * as $2 from "./routes/api/list-images.ts";
import * as $3 from "./routes/api/list-interactive.ts";
import * as $4 from "./routes/api/list-videos.ts";
import * as $5 from "./routes/api/video/[filename].ts";
import * as $6 from "./routes/dynamic.tsx";
import * as $7 from "./routes/index.tsx";
import * as $8 from "./routes/static.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/FullscreenImage.tsx";
import * as $$2 from "./islands/FullscreenVideo.tsx";
import * as $$3 from "./islands/Image.tsx";
import * as $$4 from "./islands/Interactive.tsx";
import * as $$5 from "./islands/Video.tsx";

const manifest = {
  routes: {
    "./routes/api/image/[filename].ts": $0,
    "./routes/api/interactive/[...folder].ts": $1,
    "./routes/api/list-images.ts": $2,
    "./routes/api/list-interactive.ts": $3,
    "./routes/api/list-videos.ts": $4,
    "./routes/api/video/[filename].ts": $5,
    "./routes/dynamic.tsx": $6,
    "./routes/index.tsx": $7,
    "./routes/static.tsx": $8,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/FullscreenImage.tsx": $$1,
    "./islands/FullscreenVideo.tsx": $$2,
    "./islands/Image.tsx": $$3,
    "./islands/Interactive.tsx": $$4,
    "./islands/Video.tsx": $$5,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
